### ISSUE TITLE
Add Pos change for Lvl too

### ISSUE THREAD

**Issue by xR4YM0ND** [Globox1997/TravelerZ#1]
### Make sure you are not opening a duplicate.

- [X] I have searched the issue tracker and did not find an issue describing my bug.

### Description of your suggestion.

If you change the title the lvl is so lonely and in the way.
I wanna change the position as well ^^

**Comment by Globox1997** [comment]
so you want to separately change the position of the title and subtitle?

**Comment by xR4YM0ND** [comment]
There is no subtitle pos.

Currently the subtitle has a fixed position

**Comment by Globox1997** [comment]
Fixed.
